name: Repository Metrics Tracker

on:
  # Run on any commit to main branch
  push:
    branches:
      - main
  # Run on schedule
  schedule:
    # Run daily at midnight
    - cron: '0 0 * * *'
  # Allow manual trigger
  workflow_dispatch:

# Add permissions for the GitHub token
permissions:
  contents: write

jobs:
  track-metrics:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true  # Ensure a clean working copy
          fetch-depth: 1  # Shallow clone for faster checkout
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub tabulate PyYAML
      
      - name: Run metrics collection
        run: |
          echo "Starting metrics collection..."
          echo "GitHub Repository: $GITHUB_REPOSITORY"
          echo "Running with organization specified in config..."
          # Force refresh timestamp to prevent caching
          TIMESTAMP=$(date +%s)
          python scripts/collect_repo_metrics.py --config config/repos.yaml --refresh $TIMESTAMP
          
          # Print the contents of the metrics report file
          echo "========== GENERATED METRICS REPORT =========="
          cat metrics_report.md
          echo "=============================================="
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
          GITHUB_ORG: metricscollection
      
      - name: Save metrics to artifact
        uses: actions/upload-artifact@v4
        with:
          name: repository-metrics
          path: metrics_report.md
      
      # Commit the metrics report back to the repository
      - name: Commit metrics report
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          
          echo "Current git status:"
          git status
          
          # Make sure we're working with the latest files
          git pull || true
          
          # Add and commit the metrics report
          echo "Adding metrics_report.md to git"
          git add metrics_report.md
          
          # Commit with timestamp to avoid identical commits
          TIMESTAMP=$(date +%s)
          git commit -m "Update repository metrics report [$TIMESTAMP]" || echo "No changes detected"
          
          # Push the changes
          echo "Pushing changes to repository"
          git push || echo "Push failed - trying with force"
          
          # If regular push fails, try with force
          if [ $? -ne 0 ]; then
            echo "Attempting force push..."
            git push --force
          fi
          
          # Verify the push was successful
          echo "Final git status:"
          git status
