name: Repository Metrics Tracker

on:
  # Run on any commit to main branch
  push:
    branches:
      - main
  # Run on schedule
  schedule:
    # Run daily at midnight
    - cron: '0 0 * * *'
  # Allow manual trigger
  workflow_dispatch:

# Add permissions for the GitHub token
permissions:
  contents: write

jobs:
  track-metrics:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true  # Ensure a clean working copy
          fetch-depth: 1  # Shallow clone for faster checkout
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub tabulate PyYAML
      
      - name: Run metrics collection
        run: |
          echo "Starting metrics collection..."
          echo "GitHub Repository: $GITHUB_REPOSITORY"
          echo "Running with organization specified in config..."
          # Run collection script
          python scripts/collect_repo_metrics.py --config config/repos.yaml
          
          # Print the contents of the metrics report file
          echo "========== GENERATED METRICS REPORT =========="
          cat metrics_report.md
          echo "=============================================="
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
          GITHUB_ORG: metricscollection
      
      - name: Save metrics to artifact
        uses: actions/upload-artifact@v4
        with:
          name: repository-metrics
          path: metrics_report.md
      
      # Optional: Commit the results back to the repository
      - name: Commit metrics report
        if: success()
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          
          # First, reset the repo to make sure we're working with a clean state
          git fetch origin
          git reset --hard origin/${GITHUB_REF#refs/heads/}
          
          # Check if metrics_report.md exists, create if it doesn't
          if [ ! -f "metrics_report.md" ]; then
            echo "# Repository Metrics Report" > metrics_report.md
            echo "Initial report creation" >> metrics_report.md
          fi
          
          # Add metrics report to a clean working directory
          git add metrics_report.md
          
          # Add timestamp to commit message to avoid identical commits
          TIMESTAMP=$(date +%s)
          git commit -m "Update repository metrics report [$TIMESTAMP]" || echo "No changes to commit"
          
          # Push changes directly
          git push origin HEAD:${GITHUB_REF#refs/heads/} || git push --force origin HEAD:${GITHUB_REF#refs/heads/}
