name: Repository Metrics Tracker

on:
  # Run on any commit to main branch
  push:
    branches:
      - main
  # Run on schedule
  schedule:
    # Run daily at midnight
    - cron: '0 0 * * *'
  # Allow manual trigger
  workflow_dispatch:

# Add permissions for the GitHub token
permissions:
  contents: write

jobs:
  track-metrics:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub tabulate PyYAML
      
      - name: Run metrics collection
        run: |
          echo "Starting metrics collection..."
          echo "GitHub Repository: $GITHUB_REPOSITORY"
          echo "Running with organization specified in config..."
          python scripts/collect_repo_metrics.py --config config/repos.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
          GITHUB_ORG: metricscollection
      
      - name: Save metrics to artifact
        uses: actions/upload-artifact@v4
        with:
          name: repository-metrics
          path: metrics_report.md
      
      # Optional: Commit the results back to the repository
      - name: Commit metrics report
        if: success()
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          # Pull the latest changes with rebase strategy
          git pull --rebase origin ${GITHUB_REF#refs/heads/}
          git add metrics_report.md
          git commit -m "Update repository metrics report" || echo "No changes to commit"
          # Push changes
          git push origin HEAD:${GITHUB_REF#refs/heads/}
